### ISSUE TITLE
make Satori hostname available as output in DataStore resource

### ISSUE THREAD

**Issue by chitender** [SatoriCyber/terraform-provider-satori#27]
Hi
we are using terraform-provider-satori module to automate dataStore creation on Satori for different database servers when ever we onboard new envs.

at present we are not able to Satori Hostname of a dataStore which we are creating through terraform. this is very crucial for us because we need to use Satori Hostname in our product automation.

please help us to get this included in terraform module output.

**Comment by otlg** [comment]
Hi, sorry for the late response.
The Satori Hostname is now available under the datastore resource.
